services:
  dockerizedcrud:
    image: bkapps/dockerizedcrud
    container_name: dockerizedcrud
    networks:
     - backend
    ports:
     - "8082:80"
  mysqldb:
     image: mysql 
     container_name: mysqldb
     volume: mysqlproductdbdata:/var/lib/mysql 
     environments: 
       -MYSQL_ROOT_PASSWORD= mysecret
     networks:
      - backend
  

networks:
  frontend:
    # Use a bridge driver
    driver: bridge
  backend:
    driver: bridge  
volumes:
  mysqlproductdbdata: {}           